version: '3.9'

services:
  ommsoe_db:
    image: mariadb:10.2.44
    ports:
      - 3308:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=wassan@123#
      - MYSQL_DATABASE=ommsoe
